#+title: C言語練習

* 学習の流れ
** 最初のプログラムと仕様情報
** 変数の宣言
** 関数
** 条件分岐
** 繰り返し
** 配列
** 構造体,共用体
** ポインタ
** 修飾
** コンパイルの流れ
*** ライブラリのリンク
** デバッガ(GDB)
** 総合

* 最初のプログラムと情報

helloworld.c

$ gcc -Wall helloworld.c
$ ./a.out

** 実行ファイルができるまでの各工程
最初はそこまで気にしなくてよいです。

1. プリプロセス(ヘッダファイルの処理など)
     $ gcc -E 

2. コンパイル(.c -> .S)(アセンブラ)
     $ gcc -S

3. アセンブル(.s -> .o)(オブジェクトファイルの生成)
     $ gcc -c

4. リンク
    自分もよくわかっていないので、詳しくは説明できません。

上記のオプションはgccのマニュアルにも記載がありますし、
ヘルプオプション(gcc --help)でも確認できます。

マニュアルやヘルプにはアセンブラへの変換をコンパイルと呼んでいますが、
実行ファイルの作成までをコンパイルといったり、オブジェクトファイルまでを
コンパイルと言ったり色々です。なので、話の文脈で判断する必要があると思います。

** 仕様情報
私はこれまでC言語の仕様を気にしてコードを書いたことは実際にはありません。
使用しているGCC 9.3.0は C11にGNUの拡張を加えたものがデフォルトになっているそうです。

　gccのinfoの「2.1 C Language」で確認できます。(gcc info)

仕様のドラフト版は以下からダウンロードできるのでダウンロードしてみて下さい。

　　仕様のドラフト

　　  ISO C Working Group (http://www.open-std.org/jtc1/sc22/wg14/)
　　    9899: Programming Language C
　　      C11	ISO/IEC 9899:2011	N1570 [2011-04-04]

N1570のリンクからN1570.pdfが取得できます。

** 小さなプログラム
シェルは最後に実行したプログラムの終了状態を$?に持っています。
以下のような感じです。

例1
$ true 
$ echo $?
0
$ false 
$ echo $?
1

例2
$ echo abc | grep a; echo $?
abc
0
$ echo abc | grep d; echo $?
1

main関数の戻り値で返す値がプログラムの終了状態となります。

** 問題
   1. 終了状態 0 を返すプログラムを作成しなさい。
   2. 終了状態 1 を返すプログラムを作成しなさい。
   3. 1 + 2 の計算結果を終了状態として返すプログラムを作成しなさい。
   4. 1から10までの整数の和を終了状態として返すプログラムを作成しなさい。

* 変数の宣言

variable.c

「6.7.2 Type specifiers」

** printf
printfは画面にプログラムの情報を出力するのに使える。
最初の頃は、自分の頭でのプログラムの動作と実際のプログラムの動作が一致しないことが多い。
その際、printfで状況を見ていくのは理解を助ける。

実業務でプログラムを書くようになっても自分の頭とプログラムの動作が一致しないことは起きる(バグ)。
慣れて来ると、デバッガを使ってプログラムの動作を確認する方法を取ることがあるが、
状況によりけりである。printfの出力に慣れていて損はない。

*** マニュアル
以下の用にするとコマンドのprintfが引っかかる。

$ man printf

なのでセクションを指定する。

$ man 3 printf

各セクションについてはmanのマニュアルを見てみよ。

       2   システムコール (カーネルが提供する関数)
       3   ライブラリー呼び出し (プログラムライブラリーに含まれる関数)

インフラ系の人はセクション5を見ることがあるかもしれない。(man hosts)

       5   File formats and conventions, e.g. /etc/passwd

** コメント

「6.4.9 Comments」

*** 1行コメント
   // ........

*** 複数行対応
   /* xxxxxx */

   /* aaaaaa
      zzzzzz
    */

*** その他

#if 0

  #if から #endif までのコードを無効にする。

#endif

** 問題
 1. 整数値を変換指定を%dから%xに変えて実行してみよ。
 2. フラグ文字(0)を使用してみよ。

* 関数 : 抽象化
関数(function)には、機能や働きという意味があります。
C言語における関数も同じで、一連の処理をまとめて、機能や働きを実現するためのものとなります。

例えば、printf関数は、指定された書式(f:format)で出力(print)する機能を持った関数ということになります。

** 関数と抽象化
関数の利用者は関数内にまとめられた処理について基本的には気にする必要がありません。

関数は名が体を表した関数は、いい関数。

** 関数定義

*** 実装
戻り値の型 関数名(引数の型 引数の名前)
{
  各種処理;

  return 戻り値;
}

戻り値が不要な場合は戻り値の型を void とします。
この場合は、return; を記述するか、return文を省略できます。

**** 1を返すmain関数(return1.c)
int main(void)
{
  return 1;
}

***** 実行例
$ gcc -Wall return1.c -o return1
$ ./return1 ; echo $?
1

*** プロトタイプ宣言
ファイルの先頭側で定義した関数1からファイルの後の方で定義した関数2を使用すると、
コンパイル時に警告:暗黙の型宣言がでます。これは、1のコンパイル時に関数2の型情報が無いためにでます。

この様な問題を回避するため、関数の型情報をプロトタイプ宣言としてファイルの先頭の方に記述します。

**** 例 : 暗黙の宣言(implicit declaration)
$ cat implicit.c 
int main(void)
{
  return f();
}

int f(void)
{
  return 1;
}

$ gcc -Wall f.c 
f.c: In function ‘main’:
f.c:3:10: warning: implicit declaration of function ‘f’ [-Wimplicit-function-declaration]
    3 |   return f();
      |          ^

**** 例 : プロトタイプ宣言
int f(void);

int main(void)
{
  return f();
}

int f(void)
{
  return 1;
}

$ gcc -Wall prototype.c 

*** 問題

  1. Hello world!
     1. 「Hello, world!」と標準出力に出力するプログラムを書いて下さい。
         main関数の中に直接実装してかまいません。

     2. 「Hello, world!」出力部分をprintHello関数として実装し、
         main関数から呼び出すようにして下さい。関数の型は以下の様にして下さい。

            void printHello(void)

  2. 2つの整数の和を計算するadd関数を実装し、main関数で呼び出してみなさい。

  3. 角度を度数の単位からラジアン単位に変換する関数を実装しなさい。

  4. 数値も文字を受け取り整数値として返す関数を実装しなさい。

     1. 0から9の文字をprintfの10進表記で出力させてみなさい。
	出力された結果から文字と値の関係性を考えてみよ。

  5. 標準入力から文字を取得する以下の関数を使ってみよ。

     $ man getchar

** モジュール, ライブラリ
- モジュール *.c
- ライブラリ
  .oを集めたもの

  - 静的 :  .a
  - 共有 : .so

** 関数型スタイルと再帰
変数への代入を行わないスタイル

関数型言語の場合は末尾再帰がスタックを使用しないgotoになるが、
C言語の場合はそうはならないので、再帰呼出しが深くなりスタック領域を
使い果たすとプログラムが異常終了する。

*** 再帰
**** 0からnまでの整数の和を求める関数

sum(n) = n + sum(n-1)  (n != 0)
sum(0) = 0             (n == 0)

具体的にすると

sum(10) = 10 + sum(9)
               9 + sum(8)
                   8 + sum(7)
:

**** 1からnまでの整数の積を求める関数

prod(n) = n * prod(n-1)  (n != 1)
prod(1) = 1              (n == 1)

* 条件分岐

「6.8.4 Selection statements」

** if, if〜else, if〜else if〜


** 例題 : 偶数判定
   1. 受け取った整数が偶数化どうかを判定する関数isEvenを作成せよ。
   2. 消費税を計算する関数 int calcTaxを作成せよ。
      税率は,軽減税率対象 8%, その他は10%とせよ。
   3. 配送料金
      市内である : {YES, NO}
      空輸である : { YES, NO}
      重さが10Kg超え : { YES, NO}

* 繰り返し

「6.8.5 Iteration statements」

** while
** for

** 問題
  1. 複利計算
  2. 掛け算九九
  3. 図形の描画
     問題を解くにあたり必要な関数は自由に実装せよ。
     1. 横棒
     2. 四角形
     3. 直角三角形
     4. 二等辺三角形
     5. 平行四辺形

* 配列
同じ種類の複数のデータをまとめたもの

** 問題
  1. 整数の配列から最大値の情報を返す関数を実装し、main関数から呼び出してみなさい。
  2. 2点間のデータの平均値で補完

     1. 2点間のデータを平均値で補完する関数を作成し、main関数から呼び出してみなさい。
     2. データを標準入力から読み出せるようにしなさい。
     3. 作成したプログラムの出力をグラフ化してみなさい。
     4. 作成すたプログラムをパイプを通して処理させてみなさい。

* 構造体
別の種類のデータを一つにまとめたもの

** 問題 
   統計データ



* ポインタ
ポインタとは、ポイントするモノ。
ポイントしているものは、メモリアドレス

変数とは?
人間は識別子が理解しやすい。
コンピュータはアドレス情報で動いている。

これまでの変数ではだめなの?
 1. これまでの変数はどこにあったのか?
 2. 1MBのデータを関数の引数で渡したとするとどうなるかを考えてみよ。

ポインタを使用することでできること。



** 問題
  1. 微分


* 総合
** #includeって何してるの?

** 簡易cat
** CDプレーヤーのモデル
